added wordpres

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -59,6 +59,9 @@ jobs:
           IONOS_ENDPOINT: op://K8s/ionos/IONOS_ENDPOINT
           MARIADB_USERNAME: op://K8s/ionos/MARIADB_USERNAME
           MARIADB_PASSWORD: op://K8s/ionos/MARIADB_PASSWORD
+          NODE_ONE: op://K8s/ionos/NODE_ONE
+          NODE_TWO: op://K8s/ionos/NODE_TWO
+          NODE_THREE: op://K8s/ionos/NODE_THREE
         
       - name: Print environment variables with masked secrets
         run: |
@@ -71,6 +74,9 @@ jobs:
           echo "AWS_REGION: $AWS_REGION"
           echo "MARIADB_USERNAME: $MARIADB_USERNAME"
           echo "MARIADB_PASSWORD: $MARIADB_PASSWORD"
+          echo "NODE_ONE: $NODE_ONE"
+          echo "NODE_TWO: $NODE_TWO"
+          echo "NODE_THREE: $NODE_THREE"
 
       - name: Verify Secrets Loaded
         run: |
@@ -93,6 +99,18 @@ jobs:
           fi
           if [ -z "$IONOS_TOKEN" ]; then
             echo "ERROR: IONOS_TOKEN is empty"
+            exit 1
+          fi
+          if [ -z "$NODE_ONE" ]; then
+            echo "ERROR: NODE_ONE is empty"
+            exit 1
+          fi
+          if [ -z "$NODE_TWO" ]; then
+            echo "ERROR: NODE_TWO is empty"
+            exit 1
+          fi
+          if [ -z "$NODE_THREE" ]; then
+            echo "ERROR: NODE_THREE is empty"
             exit 1
           fi
           echo "Secrets loaded successfully!"
